
- name: Configurar servidor de aplicação
  hosts: app
  become: yes

  tasks:
    - name: Instalar Apache2
      apt:
        name: apache2
        state: present

    - name: Iniciar e habilitar Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Copiar página inicial personalizada
      template:
        src: "../templates/index.html.j2"
        dest: /var/www/html/index.html
        mode: 0644

    - name: Instalar autofs
      apt:
        name: autofs
        state: present

    - name: Iniciar e habilitar serviço autofs
      service:
        name: autofs
        state: started
        enabled: yes

    - name: Criar ponto de montagem /var/nfs
      file:
        path: /var/nfs
        state: directory

    - name: Configurar autofs principal
      lineinfile:
        path: /etc/auto.master
        line: '/var/nfs /etc/auto.nfs'
        state: present
        insertafter: EOF

    - name: Configurar mapeamento NFS
      copy:
        dest: /etc/auto.nfs
        content: "nfs -fstype=nfs,rw,soft,intr 192.168.56.131:/dados/nfs"
        mode: 0644
      notify: restart autofs

  handlers:
    - name: restart autofs
      service:
        name: autofs
        state: restarted

